name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'catgpt/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          YC_CR_REGISTRY: ${{ vars.YC_CR_REGISTRY }}
        with:
          context: catgpt
          push: true
          provenance: false
          tags: cr.yandex/$YC_CR_REGISTRY/catgpt:latest
